name: 'Build'

on:
  push:
    branches:
      - 'aku-test'
  pull_request:
    branches:
      - 'aku-test'

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
          npm run build
